
name: tests

on: [push, pull_request]


jobs:
  black:
    name: Reformat with Black and Isort
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python_version: "3.8"
      - run: "python -m pip install black"
        name: Install black
      - run: "python -m black -l 99 ."
        continue-on-error: true
        name: Reformatting with black
      - run: "python -m pip install isort"
        name: Install Isort
      - run: "python -m isort ."
        continue-on-error: true
        name: Reformatting with Isort
      - name: Commit changes
        continue-on-error: true
        run: |
          git config --local committer.email "noreply@github.com"
          git config --local committer.name "GitHub"
          git config --local author.email "${{ github.actor }}@users.noreply.github.com"
          git config --local author.name "{{ github.actor }}"
          git add -A
          git commit -m "Style Reformatting"
          git push "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:${GITHUB_REF#refs/heads/}

  lint_python:
    name: Lint Python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.ref }}
      - uses: actions/setup-python@v1
        with:
          python_version: "3.8"
      - run: "python -m pip install git+https://github.com/pycqa/pyflakes@1911c20#egg=pyflakes git+https://github.com/pycqa/pycodestyle@d219c68#egg=pycodestyle git+https://gitlab.com/pycqa/flake8@3.7.9#egg=flake8"
        name: Install Flake8
      - run: "python -m flake8 . --count --select=E9,F7,F82 --show-source"
        name: Flake8 Linting
